version: 2
jobs:
  build:
    working_directory: ~/kafka-avro
    docker:
      - image: circleci/node:8.16
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start kafka and schema-registry
          command: docker-compose up -d
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@6.10'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install libreries requierd to build node-librdkafka
          command: 'sudo apt-get update && sudo apt-get -y install libsasl2-dev libssl-dev'
      - run:
          name: Install projects dependencies
          command: 'npm install'
      - setup_remote_docker
      - run:
          name: Add hostnames for kafka
          command: echo 127.0.0.1 kafka | sudo tee -a /etc/hosts && echo 127.0.0.1 schema-registry | sudo tee -a /etc/hosts && echo 127.0.0.1 zookeeper | sudo tee -a /etc/hosts
      run:
        name: Giving kafka and schema-registry addtional 30 seconds to start
        command: sleep 30
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
